# Generated by Django 5.0.6 on 2024-05-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signupf',
        ),
    ]
