# Generated by Django 5.0.6 on 2024-05-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_signupf_password_alter_signupf_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupf',
            name='ConfirmPassword',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signupf',
            name='Password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='signupf',
            name='Username',
            field=models.CharField(max_length=15),
        ),
    ]
