# Generated by Django 5.0.6 on 2024-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_signupf_confirmpassword_alter_signupf_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupf',
            name='ConfirmPassword',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signupf',
            name='Password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signupf',
            name='Username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
