# Generated by Django 5.0.6 on 2024-05-31 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_signupf_confirmpassword_alter_signupf_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupf',
            old_name='ConfirmPassword',
            new_name='Confirm_Password',
        ),
        migrations.AddField(
            model_name='signupf',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
