# Generated by Django 5.0.6 on 2024-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_confirmpassword_signupf_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupf',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='signupf',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='signupf',
            name='id',
        ),
        migrations.AlterField(
            model_name='signupf',
            name='Confirm_Password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signupf',
            name='Password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signupf',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
