# Generated by Django 5.0.6 on 2024-05-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_signupf_date_remove_signupf_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupf',
            name='ID',
            field=models.CharField(default=' ', max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
