# Generated by Django 5.0.6 on 2024-06-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_id_signupf_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
