# Generated by Django 5.0.6 on 2024-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Message', models.TextField(default=' ')),
            ],
        ),
        migrations.DeleteModel(
            name='contactmodel',
        ),
    ]
