# Generated by Django 5.0.6 on 2024-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_feedmodel_delete_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmodel',
            name='Message',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
