# Generated by Django 5.0.6 on 2024-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_feedmodel_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username1', models.CharField(max_length=25)),
                ('Password1', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='signupf',
            new_name='signupmodel',
        ),
    ]
