# Generated by Django 5.0.6 on 2024-06-05 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_password1_loginmodel_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 13, 27, 48, 843642)),
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 13, 27, 48, 844641)),
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 13, 27, 48, 842646)),
        ),
    ]
