# Generated by Django 5.0.6 on 2024-06-05 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_feedmodel_datetime_loginmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 14, 24, 30, 807346)),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 14, 24, 30, 807346)),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 14, 24, 30, 807346)),
        ),
    ]
