# Generated by Django 5.0.6 on 2024-06-13 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_feedmodel_datetime_alter_loginmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 21, 48, 6, 520011)),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 21, 48, 6, 520011)),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 21, 48, 6, 520011)),
        ),
    ]
